[workspace]
resolver = "2"
members = ["crates/app"]


[workspace.dependencies]
tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros"] }

lambda_runtime = "0.13.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["raw_value"] }
