[source.crates-io]
replace-with = "vendored-sources"

[source."git+ssh://git@github.com/tacogips/dep-lambda-container-rust.git?branch=main"]
git = "ssh://git@github.com/tacogips/dep-lambda-container-rust.git"
branch = "main"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
[net]
git-fetch-with-cli = true
